name = "Test song"
filename = "territory.mp3"

arrows = [
    { click_time = 2.30, speed = "Slow", direction = "Up" },
    { click_time = 3.30, speed = "Fast", direction = "Left" },
    { click_time = 4.30, speed = "Slow", direction = "Right" },
    { click_time = 5.30, speed = "Slow", direction = "Up" },
    { click_time = 6.30, speed = "Medium", direction = "Up" },
    { click_time = 9.00, speed = "Slow", direction = "Left" },
    { click_time = 10.00, speed = "Slow", direction = "Right" },
    { click_time = 10.50, speed = "Medium", direction = "Right" },
    { click_time = 11.00, speed = "Slow", direction = "Up" },
    { click_time = 11.00, speed = "Slow", direction = "Down" },
]
